In [1]:
!pip install pymongo

Collecting pymongo
  Downloading pymongo-4.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)
  Downloading dnspython-2.7.0-py3-none-any.whl.metadata (5.8 kB)
Downloading pymongo-4.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 19.4 MB/s eta 0:00:00
Downloading dnspython-2.7.0-py3-none-any.whl (313 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.6/313.6 kB 11.4 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.7.0 pymongo-4.10.1

In [22]:
from pymongo import MongoClient

# Inisialisasi client dan koneksi ke database
client = MongoClient('mongodb+srv://nasywaajihaan:#Nasywaa12@cluster0.764e0.mongodb.net/')
db = client['company_db']
collection = db['employees']

# Contoh untuk memastikan koneksi
print('Connected to MongoDB')

Connected to MongoDB

In [23]:
# Contoh data karyawan yang akan dimasukkan
employee_data = {
    "name": "Jasmine",
    "age": 25,
    "position": "Software Engineer",
    "salary": 70000
}

# Menambahkan data ke koleksi
collection.insert_one(employee_data)
print("Data inserted successfully")

Data inserted successfully

In [24]:
# Contoh Query Data
for employee in collection.find():
    print(employee)

{'_id': ObjectId('673b038c8d72faf0150a9308'), 'name': 'Jasmine', 'age': 25, 'position': 'Software Engineer', 'salary': 70000}

In [27]:
additional_employees = [
    {'name': 'sywuul', 'department': 'HR', 'age': 20, 'salary': 5200},
    {'name': 'bintang', 'department': 'IT', 'age': 28, 'salary': 6000},
    {'name': 'jangki', 'department': 'Finance', 'age': 30, 'salary': 4800},
]

# Menginsert data ke dalam koleksi
collection.insert_many(additional_employees)
print('Data tambahan telah dimasukkan')

Data tambahan telah dimasukkan

In [28]:
# Contoh Query Data
for employee in collection.find():
    print(employee)

{'_id': ObjectId('673b038c8d72faf0150a9308'), 'name': 'Jasmine', 'age': 25, 'position': 'Software Engineer', 'salary': 70000}
{'_id': ObjectId('673b04478d72faf0150a9309'), 'name': 'sywuul', 'department': 'HR', 'age': 20, 'salary': 5200}
{'_id': ObjectId('673b04478d72faf0150a930a'), 'name': 'bintang', 'department': 'IT', 'age': 28, 'salary': 6000}
{'_id': ObjectId('673b04478d72faf0150a930b'), 'name': 'jangki', 'department': 'Finance', 'age': 30, 'salary': 4800}

In [29]:
# Update gaji karyawan
collection.update_one({'name': 'sywuul'}, {'$set': {'salary': 5000}})
print('Gaji telah diupdate')

for employee in collection.find():
    print(employee)

Gaji telah diupdate
{'_id': ObjectId('673b038c8d72faf0150a9308'), 'name': 'Jasmine', 'age': 25, 'position': 'Software Engineer', 'salary': 70000}
{'_id': ObjectId('673b04478d72faf0150a9309'), 'name': 'sywuul', 'department': 'HR', 'age': 20, 'salary': 5000}
{'_id': ObjectId('673b04478d72faf0150a930a'), 'name': 'bintang', 'department': 'IT', 'age': 28, 'salary': 6000}
{'_id': ObjectId('673b04478d72faf0150a930b'), 'name': 'jangki', 'department': 'Finance', 'age': 30, 'salary': 4800}

In [30]:
# Menghapus karyawan yang berusia di bawah 25 tahun
collection.delete_many({'age': {'$lt': 25}})
print('Karyawan di bawah 25 tahun telah dihapus')

for employee in collection.find():
    print(employee)

Karyawan di bawah 25 tahun telah dihapus
{'_id': ObjectId('673b038c8d72faf0150a9308'), 'name': 'Jasmine', 'age': 25, 'position': 'Software Engineer', 'salary': 70000}
{'_id': ObjectId('673b04478d72faf0150a930a'), 'name': 'bintang', 'department': 'IT', 'age': 28, 'salary': 6000}
{'_id': ObjectId('673b04478d72faf0150a930b'), 'name': 'jangki', 'department': 'Finance', 'age': 30, 'salary': 4800}

In [31]:
# Query Aggregation untuk mencari rata-rata gaji per departemen
pipeline = [
    {'$group': {'_id': '$department', 'average_salary': {'$avg': '$salary'}}}
]
for result in collection.aggregate(pipeline):
    print(result)

{'_id': None, 'average_salary': 70000.0}
{'_id': 'IT', 'average_salary': 6000.0}
{'_id': 'Finance', 'average_salary': 4800.0}

{'_id': 'IT', 'average_salary': 6000.0}
{'_id': None, 'average_salary': 70000.0}
{'_id': 'Finance', 'average_salary': 4800.0}

{'_id': 'Finance', 'average_salary': 4800.0}

In [32]:
# 4 LATIHAN TUGAS TAMBAHAN
products = [
    {'name': 'Laptop', 'category': 'Elektronik', 'price': 1000},
    {'name': 'HP', 'category': 'Elektronik', 'price': 700},
    {'name': 'Tablet', 'category': 'Elektronik', 'price': 300},
    {'name': 'Earphone', 'category': 'Aksesoris', 'price': 150},
    {'name': 'Jam Tangan Pintar', 'category': 'Aksesoris', 'price': 250},
    {'name': 'Kursi Meja', 'category': 'Perabot', 'price': 200},
    {'name': 'Mesin Kopi', 'category': 'Peralatan', 'price': 120},
    {'name': 'Blender', 'category': 'Peralatan', 'price': 80},
    {'name': 'Buku', 'category': 'Alat Tulis', 'price': 20},
    {'name': 'Pulpen', 'category': 'Alat Tulis', 'price': 5}
]

collection_products = db['products']
collection_products.insert_many(products)
print('Data produk telah dimasukkan')

Data produk telah dimasukkan

In [33]:

# Menghitung rata-rata harga produk
average_price = collection_products.aggregate([
    {'$group': {'_id': None, 'average_price': {'$avg': '$price'}}}
]).next()['average_price']

# Query untuk menemukan produk dengan harga di atas rata-rata
products_above_average = collection_products.find({'price': {'$gt': average_price}})

print(f'Rata-rata harga produk: {average_price}')
print('Produk dengan harga di atas rata-rata:')
for product in products_above_average:
    print(product)

Rata-rata harga produk: 282.5
Produk dengan harga di atas rata-rata:
{'_id': ObjectId('673b04978d72faf0150a930c'), 'name': 'Laptop', 'category': 'Elektronik', 'price': 1000}
{'_id': ObjectId('673b04978d72faf0150a930d'), 'name': 'HP', 'category': 'Elektronik', 'price': 700}
{'_id': ObjectId('673b04978d72faf0150a930e'), 'name': 'Tablet', 'category': 'Elektronik', 'price': 300}

In [34]:
pipeline = [
    {'$group': {'_id': '$category', 'total_products': {'$sum': 1}}}
]

total_products_per_category = collection_products.aggregate(pipeline)

print('Total produk dalam setiap kategori:')
for result in total_products_per_category:
    print(result)

Total produk dalam setiap kategori:
{'_id': 'Perabot', 'total_products': 1}
{'_id': 'Elektronik', 'total_products': 3}
{'_id': 'Peralatan', 'total_products': 2}
{'_id': 'Alat Tulis', 'total_products': 2}
{'_id': 'Aksesoris', 'total_products': 2}

In [35]:
# 5
# Menambahkan data karyawan ke dalam koleksi employees
employees = [
    {'name': 'Ali', 'department': 'Finance', 'age': 26, 'salary': 4500},
    {'name': 'Alex', 'department': 'HR', 'age': 35, 'salary': 5200},
    {'name': 'Caca', 'department': 'IT', 'age': 34, 'salary': 6000},
    {'name': 'kiki', 'department': 'Finance', 'age': 31, 'salary': 4800},
    {'name': 'Hujan', 'department': 'IT', 'age': 30, 'salary': 5500},
    {'name': 'Budi', 'department': 'Marketing', 'age': 24, 'salary': 4900},
    {'name': 'Neosantara', 'department': 'HR', 'age': 27, 'salary': 3900},
    {'name': 'Dingding', 'department': 'IT', 'age': 29, 'salary': 6200},
]

# Menyisipkan data karyawan ke dalam koleksi
collection.insert_many(employees)
print('Data karyawan telah dimasukkan')

Data karyawan telah dimasukkan

In [36]:
# Contoh Query Data
for employee in collection.find():
    print(employee)

{'_id': ObjectId('673b038c8d72faf0150a9308'), 'name': 'Jasmine', 'age': 25, 'position': 'Software Engineer', 'salary': 70000}
{'_id': ObjectId('673b04478d72faf0150a930a'), 'name': 'bintang', 'department': 'IT', 'age': 28, 'salary': 6000}
{'_id': ObjectId('673b04478d72faf0150a930b'), 'name': 'jangki', 'department': 'Finance', 'age': 30, 'salary': 4800}
{'_id': ObjectId('673b04af8d72faf0150a9316'), 'name': 'Ali', 'department': 'Finance', 'age': 26, 'salary': 4500}
{'_id': ObjectId('673b04af8d72faf0150a9317'), 'name': 'Alex', 'department': 'HR', 'age': 35, 'salary': 5200}
{'_id': ObjectId('673b04af8d72faf0150a9318'), 'name': 'Caca', 'department': 'IT', 'age': 34, 'salary': 6000}
{'_id': ObjectId('673b04af8d72faf0150a9319'), 'name': 'kiki', 'department': 'Finance', 'age': 31, 'salary': 4800}
{'_id': ObjectId('673b04af8d72faf0150a931a'), 'name': 'Hujan', 'department': 'IT', 'age': 30, 'salary': 5500}
{'_id': ObjectId('673b04af8d72faf0150a931b'), 'name': 'Budi', 'department': 'Marketing', 'age': 24, 'salary': 4900}
{'_id': ObjectId('673b04af8d72faf0150a931c'), 'name': 'Neosantara', 'department': 'HR', 'age': 27, 'salary': 3900}
{'_id': ObjectId('673b04af8d72faf0150a931d'), 'name': 'Dingding', 'department': 'IT', 'age': 29, 'salary': 6200}

In [37]:
pipeline = [
    {'$sort': {'salary': -1}},
    {'$group': {
        '_id': {'department': '$department', 'name': '$name'},
        'salary': {'$first': '$salary'}
    }},
    {'$group': {
        '_id': '$_id.department',
        'top_employees': {'$push': {'name': '$_id.name', 'salary': '$salary'}}
    }},
    {'$project': {
        'top_employees': {'$slice': ['$top_employees', 5]}
    }}
]

top_employees = collection.aggregate(pipeline)

print('5 Karyawan dengan gaji tertinggi dalam setiap departemen:')
for result in top_employees:
    print(result)

5 Karyawan dengan gaji tertinggi dalam setiap departemen:
{'_id': None, 'top_employees': [{'name': 'Jasmine', 'salary': 70000}]}
{'_id': 'Marketing', 'top_employees': [{'name': 'Budi', 'salary': 4900}]}
{'_id': 'IT', 'top_employees': [{'name': 'Caca', 'salary': 6000}, {'name': 'bintang', 'salary': 6000}, {'name': 'Hujan', 'salary': 5500}, {'name': 'Dingding', 'salary': 6200}]}
{'_id': 'HR', 'top_employees': [{'name': 'Alex', 'salary': 5200}, {'name': 'Neosantara', 'salary': 3900}]}
{'_id': 'Finance', 'top_employees': [{'name': 'jangki', 'salary': 4800}, {'name': 'kiki', 'salary': 4800}, {'name': 'Ali', 'salary': 4500}]}

In [38]:
# Menghapus karyawan yang berusia di bawah 25 tahun
deleted_count = collection.delete_many({'age': {'$lt': 25}}).deleted_count
print(f'Jumlah karyawan yang dihapus: {deleted_count}')

Jumlah karyawan yang dihapus: 1

In [39]:
for employee in collection.find():
    print(employee)

{'_id': ObjectId('673b038c8d72faf0150a9308'), 'name': 'Jasmine', 'age': 25, 'position': 'Software Engineer', 'salary': 70000}
{'_id': ObjectId('673b04478d72faf0150a930a'), 'name': 'bintang', 'department': 'IT', 'age': 28, 'salary': 6000}
{'_id': ObjectId('673b04478d72faf0150a930b'), 'name': 'jangki', 'department': 'Finance', 'age': 30, 'salary': 4800}
{'_id': ObjectId('673b04af8d72faf0150a9316'), 'name': 'Ali', 'department': 'Finance', 'age': 26, 'salary': 4500}
{'_id': ObjectId('673b04af8d72faf0150a9317'), 'name': 'Alex', 'department': 'HR', 'age': 35, 'salary': 5200}
{'_id': ObjectId('673b04af8d72faf0150a9318'), 'name': 'Caca', 'department': 'IT', 'age': 34, 'salary': 6000}
{'_id': ObjectId('673b04af8d72faf0150a9319'), 'name': 'kiki', 'department': 'Finance', 'age': 31, 'salary': 4800}
{'_id': ObjectId('673b04af8d72faf0150a931a'), 'name': 'Hujan', 'department': 'IT', 'age': 30, 'salary': 5500}
{'_id': ObjectId('673b04af8d72faf0150a931c'), 'name': 'Neosantara', 'department': 'HR', 'age': 27, 'salary': 3900}
{'_id': ObjectId('673b04af8d72faf0150a931d'), 'name': 'Dingding', 'department': 'IT', 'age': 29, 'salary': 6200}

In [40]:
pipeline = [
    {'$group': {
        '_id': '$department',
        'total_salary': {'$sum': '$salary'},
        'average_age': {'$avg': '$age'}
    }}
]

salary_age_report = collection.aggregate(pipeline)

print('Laporan ringkas total gaji dan rata-rata umur karyawan di setiap departemen:')
for result in salary_age_report:
    print(result)

Laporan ringkas total gaji dan rata-rata umur karyawan di setiap departemen:
{'_id': 'IT', 'total_salary': 23700, 'average_age': 30.25}
{'_id': 'Finance', 'total_salary': 14100, 'average_age': 29.0}
{'_id': None, 'total_salary': 70000, 'average_age': 25.0}
{'_id': 'HR', 'total_salary': 9100, 'average_age': 31.0}